// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class ExclusoTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void excluso() {
    driver.get("https://cadastrocars.vercel.app/");
    driver.manage().window().setSize(new Dimension(1440, 780));
    driver.findElement(By.cssSelector(".carItem:nth-child(1) .pointButton")).click();
    driver.findElement(By.cssSelector(".pointWindowBtn:nth-child(2)")).click();
    assertThat(driver.switchTo().alert().getText(), is("Tem certeza que deseja excluir?"));
    driver.switchTo().alert().accept();
    driver.findElement(By.cssSelector(".carItem:nth-child(1) .pointButton")).click();
    driver.findElement(By.cssSelector(".pointWindowBtn:nth-child(2)")).click();
    assertThat(driver.switchTo().alert().getText(), is("Tem certeza que deseja excluir?"));
    driver.switchTo().alert().accept();
    driver.close();
  }
}
